export {default as HomePage} from './HomePage.jsx'
export {default as CoursesPage} from './CoursesPage.jsx'
export {default as AboutUsPage} from './AboutUsPage.jsx'
export {default as BlogsPage} from './BlogsPage.jsx'
export {default as BlogDetailPage}from './BlogDetailPage.jsx'